### PR TITLE
*: Fixed various go vet and golint warnings

### LINKED ISSUE #38: Golint Stutter Warnings
My editor warns me about our current names:

> task/task_service.go:14:6: type name will be used as task.TaskObject by other packages, and that stutters; consider calling this Object
> task/task_service.go:32:6: type name will be used as task.TaskService by other packages, and that stutters; consider calling this Service
> task/task_service.go:63:6: type name will be used as task.TaskServiceConfig by other packages, and that stutters; consider calling this ServiceConfig

I think I agree here. `TaskObject` could simply be `Task`, `TaskService` become `Service` etc.

Opinions @giantswarm/cena ?

### PR DESCRIPTION
**Pull request by zeisss**
Fixes #38. These are only renames done by `gofmt` and a few manualy reverts, e.g. to keep `TaskService` inside the `Controller` for the field name.

### CODE REVIEW

File: task/task_service.go [hunk 1]
```diff
@@ -10,67 +10,50 @@ import (
 // Action represents any work to be done when executing a task.
 type Action func() error
 
-// TaskObject represents a task that is executable.
-type TaskObject struct {
```
Comment (zeisss) [inline task/task_service.go:14]: moved to `task.go`

**Comment by zeisss** [comment]
ping @giantswarm/cena

File: task/task_service.go (hunk 1 above)
Comment (xh3b4sd) [inline task/task_service.go:14]: Why?

**Comment by xh3b4sd** [comment]
I think some changes do not make sense but I don't have strong feelings here. Go ahead.

File: task/task_service.go (hunk 1 above)
Comment (zeisss) [inline task/task_service.go:14]: the file was there and it felt logic for me to put the type `Task` into the file `task.go`. Since you ask, I will revert. there is no need for this change by itself.
