### PR TITLE
Fixes submitting of unit names

### LINKED ISSUE #124: submit blocks forever, if group already has a running slice
```
kallisto:example zeisss$ ../inagoctl --fleet-endpoint=http://172.17.8.101:49153 submit mygroup
2016-03-16 17:24:48.190 | INFO     | context.Background: Succeeded to submit group 'mygroup'.
kallisto:example zeisss$ ../inagoctl --fleet-endpoint=http://172.17.8.101:49153 start mygroup
2016-03-16 17:25:04.505 | INFO     | context.Background: Succeeded to start 1 slices for group 'mygroup': [3b5].
kallisto:example zeisss$ ../inagoctl --fleet-endpoint=http://172.17.8.101:49153 submit mygroup


^C
```

### PR DESCRIPTION
**Pull request by zeisss**
This fixes a bunch of things. Sorry for making it one PR.
# panic for empty folders

```
$ mkdir foo/
$ ../inagoctl --fleet-endpoint=${FLEET_ENDPOINT} submit -v foo
2016-03-16 18:39:51.846 | DEBUG    | context.Background: cli: starting submit
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/giantswarm/inago/cli.createSubmitRequest(0x8820836ae0, 0x75a418, 0x7fff5fbffac9, 0x3, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/code/.gobuild/src/github.com/giantswarm/inago/cli/submit.go:76 +0x49b
github.com/giantswarm/inago/cli.submitRun(0x739e00, 0x8207f5b90, 0x1, 0x3)
    /usr/code/.gobuild/src/github.com/giantswarm/inago/cli/submit.go:45 +0x10f
github.com/spf13/cobra.(*Command).execute(0x739e00, 0x8207f5a10, 0x3, 0x3, 0x0, 0x0)
    /usr/code/.gobuild/src/github.com/spf13/cobra/command.go:569 +0x85a
github.com/spf13/cobra.(*Command).ExecuteC(0x739600, 0x739e00, 0x0, 0x0)
    /usr/code/.gobuild/src/github.com/spf13/cobra/command.go:656 +0x55c
github.com/spf13/cobra.(*Command).Execute(0x739600, 0x0, 0x0)
    /usr/code/.gobuild/src/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
    /usr/code/main.go:11 +0x27
```
# you cannot do a second submit, if the first one is already started

fixes #124 + adds a test
# Adds make internal-int-test to specify your own fleet VM

well, same `make int-test`, it just doesn't boot the VM.

### CODE REVIEW

File: controller/request.go [hunk 1]
```diff
@@ -128,6 +138,10 @@ func contains(l []string, e string) bool {
 }
 
 func (c controller) ExtendWithRandomSliceIDs(req Request) (Request, error) {
+	if !req.IsSlicable() {
```
Comment (zeisss) [inline controller/request.go]: this feels ugly, and I fear we might need to put this all over the places. Lets make it working first, than fix the data model, shall we?

File: int-tests/002-update.t [hunk 2]
```diff
@@ -1,7 +1,7 @@
 Create a group to play around with.
   $ mkdir update-group
-  $ echo "[Unit]\nDescription=Inago Update Test Unit\n\n[Service]\nExecStart=/bin/bash -c \"while true; do echo Hi; sleep 10; done\"" > update-group/update-group-foo@.service
-  $ echo "[Unit]\nDescription=Inago Update Test Unit\n\n[Service]\nExecStart=/bin/bash -c \"while true; do echo Hi; sleep 10; done\"" > update-group/update-group-bar@.service
+  $ printf "[Unit]\nDescription=Inago Update Test Unit\n\n[Service]\nExecStart=/bin/bash -c \"while true; do echo Hi; sleep 10; done\"\n" > update-group/update-group-foo@.service
```
Comment (zeisss) [inline int-tests/002-update.t:3]: prints the newlines correctly

File: int-tests/003-err-submit-twice.t [hunk 3]
```diff
@@ -0,0 +1,15 @@
+We had a bug where submit would block forever, because it would check on the wrong unit files.
```
Comment (zeisss) [inline int-tests/003-err-submit-twice.t:1]: Regression TESTS :dancer:

**Comment by zeisss** [comment]
ping @giantswarm/cena

File: cli/request.go [hunk 4]
```diff
@@ -43,5 +45,9 @@ func extendRequestWithContent(fs filesystemspec.FileSystem, req controller.Reque
 		req.Units = append(req.Units, controller.Unit{Name: name, Content: content})
 	}
 
+	if len(req.Units) == 0 {
+		return controller.Request{}, errgo.Newf("No unit files found for group '%s'", req.Group)
+	}
+
```
Comment (JosephSalisbury) [inline cli/request.go:51]: We already have request validation: https://github.com/giantswarm/inago/blob/master/controller/validator.go#L87 - does it make sense to use that here?

File: controller/request.go [hunk 5]
```diff
@@ -53,6 +53,16 @@ func NewRequest(config RequestConfig) Request {
 
 var unitExp = regexp.MustCompile("@.")
 
+// IsSlicable checks whether all units of the request are sliceable (contain an @)
+func (r Request) IsSlicable() bool {
```
Comment (JosephSalisbury) [inline controller/request.go]: sliceable, not slicable

File: cli/request.go (hunk 4 above)
Comment (zeisss) [inline cli/request.go:51]: the code later checks on `req.Units[0]` and throws a panic, even before the controller is reached. So I would say yes.

File: controller/request.go (hunk 5 above)
Comment (zeisss) [inline controller/request.go]: done

**Comment by JosephSalisbury** [comment]
cool, LGTM
