### PR TITLE
fix max-growth bug

### LINKED ISSUE #213: Update can cause an extraneous slice to be created
@xh3b4sd and I had a case today where we had two slices running, and an update with min-alive=1, max-growth=0 presented an update like so:
1. [339, 591]
2. [591]
3. [0a0, 591, 72e]
4. [0a0, 72e]

It would seem that at 3, 2 additional slices were made. With max-growth=0, we would expect only one slice to have been created at this point.

### PR DESCRIPTION
**Pull request by Nesurion**
See #213

We discovered that the calculation if we are allowed to add or remove slices was faulty. The PR fixes #213 by changing the calculation formula.

### CODE REVIEW

**Comment by Nesurion** [comment]
@giantswarm/cena RFR. WFM would be super nice

File: controller/update.go [hunk 1]
```diff
@@ -72,47 +72,37 @@ func (c controller) getNumRunningSlices(ctx context.Context, req Request) (int,
...
-	if numRunning > minAlive {
-		c.Config.Logger.Debug(ctx, "controller: group removal allowed (numRunning > minAlive)")
+	if (minAlive - int(*removalInProgress)) > 0 {
+		c.Config.Logger.Debug(ctx, "controller: group removal allowed ((minAlive - int(removalInProgress)) > 0)")
 		return true, nil
 	}
 
-	c.Config.Logger.Debug(ctx, "controller: group removal not allowed (numRunning <= minAlive)")
+	c.Config.Logger.Debug(ctx, "controller: group removal not allowed ((minAlive - int(removalInProgress)) <= 0)")
 	return false, nil
```
Comment (xh3b4sd) [inline controller/update.go:89]: Do you thing we still need this methods?

File: controller/update.go [hunk 2]
```diff
@@ -348,30 +337,34 @@ func (c controller) UpdateWithStrategy(ctx context.Context, req Request, opts Up
...
 
 				break
 			}
 
 			c.Config.Logger.Debug(ctx, "controller: attempting to remove slice: %v", sliceID)
 			// remove
-			minAlive := opts.MinAlive + int(removeInProgress)
+			// we are only allowed to remove if the number of minAlive slices
+			// minus the ones, that are beeing removed right now is greater than 0
+			//=> (minAlive - int(removalInProgress)) > 0)
```
Comment (xh3b4sd) [inline controller/update.go]: `removalInProgress` -> `removeInProgress`

File: controller/update.go (hunk 1 above)
Comment (Nesurion) [inline controller/update.go:89]: I'd like to keep it in, as it was useful while writing the fix. I guess it could come in handy at some point in the future

**Comment by xh3b4sd** [comment]
LGTM

File: controller/update.go [hunk 3]
```diff
@@ -348,30 +337,34 @@ func (c controller) UpdateWithStrategy(ctx context.Context, req Request, opts Up
 
 					atomic.AddInt64(&addInProgress, -1)
 					done <- struct{}{}
-				}()
+				}(ctx)
```
Comment (xh3b4sd) [inline controller/update.go:340]: Looks like I was not clear enough. `newReq` is the one we need to pass into the goroutine scope as well.

File: controller/update.go [hunk 4]
```diff
@@ -312,29 +301,29 @@ func (c controller) UpdateWithStrategy(ctx context.Context, req Request, opts Up
...
 				return maskAny(err)
 			}
 			if ok {
-				go func() {
+				// we increase the addInProgress counter before starting the goroutine
+				// to avoid a race condition in the allowed calculation
+				atomic.AddInt64(&addInProgress, 1)
+				go func(ctx context.Context) {
 					ctx = context.WithValue(ctx, "add slice", sliceID)
 					c.Config.Logger.Debug(ctx, "controller: starting to add slice: %v", sliceID)
```
Comment (xh3b4sd) [inline controller/update.go:326]: Here `newReq.SliceIDs` should be used for logging.

File: controller/update.go [hunk 5]
```diff
@@ -348,30 +337,34 @@ func (c controller) UpdateWithStrategy(ctx context.Context, req Request, opts Up
...
+			ok, err = c.isGroupRemovalAllowed(ctx, currentSliceReq, opts.MinAlive, &removeInProgress)
 			if err != nil {
 				return maskAny(err)
 			}
 			if ok {
-				go func() {
+				// we increase the removeInProgress counter before starting the goroutine
+				// to avoid a race condition in the allowed calculation
+				atomic.AddInt64(&removeInProgress, 1)
+				go func(ctx context.Context) {
```
Comment (xh3b4sd) [inline controller/update.go:365]: Same comments as above apply also to this goroutine.

Comment (Nesurion) [inline controller/update.go:365]: @xh3b4sd please see https://github.com/giantswarm/inago/pull/243
